# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'management_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(441, 388)
        window.setStyleSheet("#window{\n"
"    background-color: #cbcbcb;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border: 1px solid black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setEnabled(True)
        self.frame.setStyleSheet("#frame{\n"
"    border: 1px solid black;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("#label {\n"
"    background-color: blue;\n"
"    color:white;\n"
"    border-radius: 10px;\n"
"}")
        self.label.setLineWidth(5)
        self.label.setObjectName("label")
        self.form = QtWidgets.QLineEdit(self.frame)
        self.form.setGeometry(QtCore.QRect(110, 70, 291, 31))
        self.form.setStyleSheet("#form{\n"
"    border-radius:10px;\n"
"    font-size:15px;\n"
"}")
        self.form.setText("")
        self.form.setFrame(True)
        self.form.setAlignment(QtCore.Qt.AlignCenter)
        self.form.setObjectName("form")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2 {\n"
"    background-color: blue;\n"
"    color:white;\n"
"    border-radius: 10px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.form_2 = QtWidgets.QLineEdit(self.frame)
        self.form_2.setGeometry(QtCore.QRect(110, 110, 291, 31))
        self.form_2.setStyleSheet("#form_2{\n"
"    border-radius:10px;\n"
"    font-size:15px;\n"
"}")
        self.form_2.setText("")
        self.form_2.setAlignment(QtCore.Qt.AlignCenter)
        self.form_2.setObjectName("form_2")
        self.button1 = QtWidgets.QPushButton(self.frame)
        self.button1.setGeometry(QtCore.QRect(40, 160, 341, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.button1.setFont(font)
        self.button1.setStyleSheet("#button1{\n"
"    background-color: blue;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}")
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.frame)
        self.button2.setGeometry(QtCore.QRect(40, 200, 341, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.button2.setFont(font)
        self.button2.setStyleSheet("#button2{\n"
"    background-color: blue;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}")
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.frame)
        self.button3.setGeometry(QtCore.QRect(40, 240, 341, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.button3.setFont(font)
        self.button3.setStyleSheet("#button3{\n"
"    background-color: blue;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}")
        self.button3.setObjectName("button3")
        self.button4 = QtWidgets.QPushButton(self.frame)
        self.button4.setGeometry(QtCore.QRect(40, 280, 341, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.button4.setFont(font)
        self.button4.setStyleSheet("#button4{\n"
"    background-color: blue;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}")
        self.button4.setObjectName("button4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label_3{\n"
"    color:white;\n"
"    background-color: blue;\n"
"    border-radius: 5px;\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_2)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "MainWindow"))
        self.label.setText(_translate("window", "      Nama"))
        self.form.setPlaceholderText(_translate("window", "Masukkan Nama "))
        self.label_2.setText(_translate("window", "    Alamat "))
        self.form_2.setPlaceholderText(_translate("window", "Masukkan Alamat"))
        self.button1.setText(_translate("window", "Tambah"))
        self.button2.setText(_translate("window", "Edit"))
        self.button3.setText(_translate("window", "Hapus"))
        self.button4.setText(_translate("window", "Cari"))
        self.label_3.setText(_translate("window", "    Management Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())

